assert-rs/assert_cli

Cargo.toml, Readme.md, src/lib.rs, tests/macro.rs
Fixes #6. I was thinking about whether to implement it as interpreting an empty string as matching any output, but I can see how many situations might call for explicitly expecting a command not to output (such as when testing a quiet mode). Is this alright?
Also, I think fuzzy matching should be a new issue. It would be a much different of an implementation than #6.
=> Option to ignore output

Readme.md
This one really got me. I spent half an hour researching if the Rust macro include system had changed somehow until realizing that I had installed a version of this library that didn't include the macro yet :relieved:
=> Update version number in README

Readme.md, src/lib.rs
This is helpful to be able to do further assertions on the result of the
call, e.g. to check the stdout using a regex.
=> Return output information from assert calls.

.travis.yml, Cargo.toml, README.md, build.rs, tests/skeptic.rs
This commit adds Readme testing using [skeptic](https://github.com/brson/rust-skeptic).
I applied some experiences from adding skeptic to other libraries, such as the .travis.yml change that prevents intermittent Travis timeouts.
Unfortunately because skeptic only allows a single interpolation position we need to decide whether we want to display examples like this:
```rust
extern crate assert_cli;
fn main() {
assert_cli::assert_cli_output("echo", &["42"], "42").unwrap();
} 
```
or like this:
```rust
assert_cli::assert_cli_output("echo", &["42"], "42").unwrap();
```
Meaning that, afaiu, we can't include `extern crate` without adding `fn main`.
=> Add skeptic support

src/diff.rs, src/errors.rs, src/lib.rs, src/output.rs
This refactors the output assertions to use a generic type, unit structs, and a new traits. Basically, type system shenanigans!
Previous discussions:
- https://github.com/killercup/assert_cli/pull/16#discussion_r107293868
- https://github.com/killercup/assert_cli/pull/16#discussion_r107294927
=> Refactor output assertions

src/lib.rs
Some tests need to run in certain directories but if you call `std::env::set_current_dir` within your test, you can hit race conditions with other tests running at the same time.  This allows you to set the current_dir only on the child process.
=> Add ability to set current_dir

README.md, src/assert.rs, src/lib.rs, src/macros.rs, src/output.rs
Reusing output assertions makes it easier to add new ones in the future.
I feel the new naming scheme this provides makes intent of the API clearer as well (`stdout().contains` vs `prints`).
This is done by creating an `OutputAssertionBuilder` that `Assertion` delegates to for creating output assertions, passing in an enum of which stream to read from.   This unfortunately meant dropping the cool type tricks that were introduced in #24.  This also required merging the storage of stdout/stderr assertions.  To accommodate this, output assertions are now appended which might be useful on its own.
=> Reuse output assertions between stdout/stderr

src/assert.rs, src/errors.rs, src/output.rs
- Show stdout/stderr on exit code failures
- Show expected/got strings for output assertions
This also includes a minor refactor to simplify `output.rs`.
=> Increase context on failures

src/assert.rs
Allows you to put the contents of a String in the program's stdin.
Fixes #26
=> Add `stdin` function

.travis.yml, Cargo.toml, README.md, src/assert.rs, src/lib.rs
Check the discussion in #27 
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>
=> Add with_env helper

src/assert.rs
Implements `Assert::ignore_status()`, which can be used to ignore whether a command exited successfully.
Fixes #23.
=> Add Assert::ignore_status() for ignoring the command status

Cargo.toml, src/assert.rs, src/bin/assert_fixture.rs, src/errors.rs, tests/cargo.rs
To help in validating this, tests have been added for `main_binary` and `cargo_binary`. 
Fixed #45
=>  fix: Remove unrelated output in main_binary 

src/assert.rs
This will help users catch missing `unwrap`s.
Fixes #66
=> fix: Make Assert `must_use`

Cargo.toml, src/diff.rs
This updates the difference dependency to version 2, which introduces a
slightly rewritten difference algorithm and was failing tests for some
crates (including this one). Hence the major version bump.
The failing test in this case was just some white space being prepended
to the output (presumably because difference added an empty string to the
beginning of its output before), so that looks more like a fix to me.
=> Update to difference v2.0

src/assert.rs, src/errors.rs, src/lib.rs, src/output.rs
This PR (mostly) keeps the same API but replaces the guts with those from #74.
Other foundational output predicate functionality is added in to help this serve as a base for further work (like regexes in #85).
=> Refactor output

README.md
- [n/A] I have created tests for any new feature, or added regression tests for bugfixes.
- [n/A] `cargo test` succeeds
- [n/A] Clippy is happy: `cargo +nightly clippy` succeeds
- [n/A] Rustfmt is happy: `cargo +nightly fmt` succeeds
Closes #88
=> Change tempdir to tempfile in readme

Cargo.toml, src/assert.rs, src/bin/assert_fixture.rs, src/diff.rs, src/errors.rs, src/lib.rs, src/output.rs
In doing so, this caught a couple places we weren't providing additional
context to an error.
This does not address the errors returned by the internal string predicates.  Those are generic `failure::Error`.
Example:
```
Assertion failed for 'wc README.md'
with: Unexpected return status: failure
stdout=''''''
stderr='''wc: README.md: No such file or directory
'''
```
BREAKING CHANGE: The error type has changed from error-chain to
`assert_cli::AssertionError`.
=> Migrate to failure 

Cargo.toml, build.rs, tests/docmatic.rs, tests/skeptic.rs
This removes quite a few dependencies from assert_cli.
```
Removing bitflags v0.9.1
Removing bitflags v1.0.3
Removing bytecount v0.2.0
Removing cargo_metadata v0.3.3
Adding docmatic v0.1.2
Removing error-chain v0.11.0
Removing fuchsia-zircon v0.3.3
Removing fuchsia-zircon-sys v0.3.3
Removing glob v0.2.11
Removing kernel32-sys v0.2.2
Removing proc-macro2 v0.3.8
Removing pulldown-cmark v0.1.2
Removing quote v0.5.2
Removing rand v0.4.2
Removing remove_dir_all v0.5.1
Removing same-file v0.1.3
Removing semver v0.8.0
Removing semver-parser v0.7.0
Removing serde_derive v1.0.51
Removing skeptic v0.13.2
Removing syn v0.13.7
Removing tempdir v0.3.7
Removing unicode-xid v0.1.0
Removing walkdir v1.0.7
Adding which v2.0.0
Removing winapi v0.2.8
Removing winapi-build v0.1.1
```
=> Replace skeptic by docmatic

src/assert.rs
I have created a separate PR for this change as requested in #107.
=> Add `example` constructor for Assert

src/diff.rs
Solves #112 
- [*] I have created tests for any new feature, or added regression tests for bugfixes.
- [*] `cargo test` succeeds
=> fix panic on diff when addind new first line

Cargo.toml, README.md
=> Mark assert_cli as deprecated
